version: '3'

services:
  web:
    build: .
    tty: true
    volumes:
      - ./:/workspace
    depends_on:
      - db
    ports:
      - '5001:5001'

  db:
    image: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: sample

  pgadmin4:
    image: dpage/pgadmin4
    ports:
      - 8888:80
    volumes:
      - pgadmin4_data:/var/lib/pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: xxxxxxxxxx@gmail.com
      PGADMIN_DEFAULT_PASSWORD: password
    depends_on:
      - db

volumes:
  postgres_data:
  pgadmin4_data:
